//
//  Persistence/WSSummary.swift · Wenshu · v0.72 SwiftData migration Phase 1
//
//  Phase 1 commit 13/21: WSSummary.
//  Mirrors `chat_summaries` table from ChatSessionStore.swift.
//
//  1↔1 to WSSession (= each session has 0 or 1 summary; = the summary
//  is regenerated when the session grows past a threshold).
//
//  Same SwiftData pattern as commit 12:
//  - Parent (WSSession.summary): @Relationship(inverse: \WSSummary.session)
//  - Child (WSSummary.session): plain Optional WSSession?

import Foundation
import SwiftData

@Model
public final class WSSummary {
    @Attribute(.unique) public var id: String
    /// FK to WSSession.sessionID (= string FK)
    var sessionID: String
    /// Summary text (= may be very long; = generated by LLM)
    var summary: String
    /// Token count of the original session (= context for the summary)
    var coveredTokenCount: Int
    /// Token count of this summary itself
    var summaryTokenCount: Int
    /// The range this summary covers: [startMessageID, endMessageID]
    var startMessageID: String
    var endMessageID: String
    /// LLM model used to generate this summary
    var modelUsed: String
    var createdAt: Date
    var updatedAt: Date

    /// Inverse relationship target (= declared on WSSession)
    var session: WSSession?

    init(id: String, sessionID: String, summary: String,
         startMessageID: String, endMessageID: String,
         coveredTokenCount: Int, summaryTokenCount: Int, modelUsed: String) {
        self.id = id
        self.sessionID = sessionID
        self.summary = summary
        self.startMessageID = startMessageID
        self.endMessageID = endMessageID
        self.coveredTokenCount = coveredTokenCount
        self.summaryTokenCount = summaryTokenCount
        self.modelUsed = modelUsed
        self.createdAt = Date()
        self.updatedAt = Date()
    }
}
