//
// Persistence/WSSummary.swift · Wenshu
//
// SwiftData @Model: chat summary per session (= 1↔1 to WSSession).
// SwiftData migration  (= see CHANGELOG.md v0.72 section
// for the full migration narrative from raw sqlite3 to SwiftData).
//

import Foundation
import SwiftData

@Model
final class WSSummary {
    @Attribute(.unique) var id: String
    /// FK to WSSession.sessionID (= string FK)
    var sessionID: String
    /// Summary text (= may be very long; = generated by LLM)
    var summary: String
    /// Token count of the original session (= context for the summary)
    var coveredTokenCount: Int
    /// Token count of this summary itself
    var summaryTokenCount: Int
    /// The range this summary covers: [startMessageID, endMessageID]
    var startMessageID: String
    var endMessageID: String
    /// LLM model used to generate this summary
    var modelUsed: String
    var createdAt: Date
    var updatedAt: Date

    /// Inverse relationship target (= declared on WSSession)
    var session: WSSession?

    init(id: String, sessionID: String, summary: String,
         startMessageID: String, endMessageID: String,
         coveredTokenCount: Int, summaryTokenCount: Int, modelUsed: String) {
        self.id = id
        self.sessionID = sessionID
        self.summary = summary
        self.startMessageID = startMessageID
        self.endMessageID = endMessageID
        self.coveredTokenCount = coveredTokenCount
        self.summaryTokenCount = summaryTokenCount
        self.modelUsed = modelUsed
        self.createdAt = Date()
        self.updatedAt = Date()
    }
}

// Apple HIG canonical Identifiable conformance for SwiftUI
// Table selection. Same rationale as WSAttachment (= the
// existing String id field already satisfies Swift's
// Identifiable; = free one-line declaration; = no
// PersistentIdentifier entanglement).
extension WSSummary: Identifiable {}
