//
//  KeylessProvidersLiveAPITests.swift · Wenshu
//
//  Live integration test: drives the full wenshu LLM-agent-style flow
//  against the real anonymous-free-tier vendor endpoints. This is the
//  test that proves "the user opens wenshu and web search works with
//  zero configuration" end-to-end.
//
//  Flow:
//    1. ToolRegistry.shared gets the WebSearchTool registered via the
//       canonical `_registryBootstrap` Task (the same path wenshu uses
//       at app launch).
//    2. We synthesize the same tool-call envelope that an LLM would
//       produce: {"action":"search","query":"Apple HIG writing tool"}.
//
//       Note: in production, this envelope is generated by the LLM
//       (= wenshu's agent runtime decides when to invoke `web_search`).
//       For this test, we hard-code the envelope to exercise the
//       downstream path without needing a real LLM API key (= keeps
//       the test free of paid API requirements per v2.5 boss OOB
//       = "no paid external dependencies, no API key requirements").
//    3. WebSearchTool.execute parses the JSON, delegates to
//       WebSearch (actor) → KeylessRing → walks the canonical ring
//       (Parallel → Exa → Keenable) and returns the first non-empty
//       hit set.
//    4. We assert the envelope is shape-correct AND that at least one
//       vendor returned at least one parseable result.
//
//  These tests run only against the LIVE internet. They are gated by
//  the `WENSHU_LIVE_API_TESTS` env var (= default off; = CI may opt in
//  explicitly). When the env var is absent, every test records a
//  "skipped (= no live API access)" issue and returns immediately,
//  matching the §11.5 known-flake pattern.
//
//  Cost: 0 (= all 3 vendors are anonymous free tiers per their docs
//  and per the 2026-09-25 live validation).
//

import Testing
import Foundation
@testable import WenshuApp

@Suite("KeylessProviders (LIVE)")
struct KeylessProvidersLiveAPITests {

    /// Run live tests only when the env var is set (= CI opt-in).
    /// Local dev runs by default do not pay for / require connectivity.
    private static var liveEnabled: Bool {
        ProcessInfo.processInfo.environment["WENSHU_LIVE_API_TESTS"] == "1"
    }

    /// Helper: race a closure against a timeout (= throws TimeoutError if the
    /// deadline elapses first). Used to avoid hangs when a vendor's MCP
    /// server expects an initialize handshake that the wenshu client
    /// hasn't yet implemented.
    private func withTimeout<T: Sendable>(
        seconds: Double,
        operation: @escaping @Sendable () async throws -> T
    ) async throws -> T {
        try await withThrowingTaskGroup(of: T?.self) { group in
            group.addTask { try await operation() }
            group.addTask {
                try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
                return nil
            }
            guard let result = try await group.next() ?? nil else {
                group.cancelAll()
                throw TimeoutError()
            }
            group.cancelAll()
            return result
        }
    }

    private struct TimeoutError: Error {}
}